### ISSUE TITLE
Add Channel logs navigation to the header bar

### ISSUE THREAD

**Issue by rikmendes** [indieweb/chat.indieweb.org#1]
it would be great to have the ability from chat.indieweb.org to switch between channels at the top of the web interface, it would give a great way for non-irc people to lurk and get used to enter by the door little by little :) maybe a simple dropdown like the Timezone drop down, so you save space on that area  ie : http://prntscr.com/bp6nhy

tantek suggested tabs & colors if activity
bear :  was concerned about progressives enhancement loss if this feature force the use of javascript.
tantek suggested that color changes could be js-dependent but tabs per channel could work fine with just HTML.

**Comment by voxpelli** [comment]
+1 on the tabs, similar to what eg. Slack does and make new activity easy to spot

**Comment by aaronpk** [comment]
Great idea! This is done now, including highlighting the tab when there's new activity in a channel you're not looking at!
