### ISSUE TITLE
Chrome display issue in Refreshed CSS

### ISSUE THREAD

**Issue by chrisaldrich** [indieweb/chat.indieweb.org#12]
Per our conversation here's a screenshot of what's happening:
![indieweb css](https://cloud.githubusercontent.com/assets/5882943/17274737/85743bb0-56a4-11e6-8573-f22c1a5d8caf.PNG)

Essentially the bar on the left is covering up most of the chat commentary, which needs to be shifted over. Doesn't seem to be happening on any of the other browsers I tested -- only chrome.

**Comment by aaronpk** [comment]
That's super weird. What version of chrome and on what OS? It looks fine for me on Chrome 51.0.2704.103 on OSX.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/indieweb/chat.indieweb.org/issues/12" class="u-in-reply-to"></a>I just pulled it up on another machine with chrome and it seems fine now.  I may have borked some of my chrome settings earlier this week while "experimenting". May be time to reinstall back to factory....
