### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by aaronpk** [indieweb/chat.indieweb.org#13]
- Index everything in elasticsearch
- Provide a search interface for doing simple log searches
- Return results across all channels in the channel group
- Results are displayed in reverse chronological order

Syntax:
- `keyword` - searches content of chat messages for this keyword
- `"quoted term"` - searches for exact match of quoted term
- `-keyword` - excludes this keyword from matches
- `nick:aaronpk` - returns results by this user
- `before:2016-08-08` `after:2016-07-07` `date:2016-08-08` - date ranges
- `channel:#indieweb` - limit results to this channel

These should be able to be combined as well.

**Comment by cweiske** [comment]
I want to extend and host a [phinde](https://github.com/cweiske/phinde) instance for chat.indieweb.org - just saying.

**Comment by aaronpk** [comment]
@cweiske go for it! You should be able to crawl the logs by looking for `rel="prev"` starting with chat.indieweb.org

The only trick is that because every line is on the date permalink as well as its own, i'm not sure what that will do to the search results. My plan was to not index the date permalinks and just index each chat line on its own. I'm not sure how that will work with a generic search engine.

**Comment by cweiske** [comment]
Now available at http://indiechat.search.cweiske.de/

**Comment by cweiske** [comment]
https://github.com/indieweb/chat.indieweb.org/pull/25/commits/307817f5a4125fed26efa04ed447cc6123e03a2e enables the search form.

**Comment by cweiske** [comment]
We can close this.
