### ISSUE TITLE
Add last-modified HTTP header and support if-modified-since requests

### ISSUE THREAD

**Issue by cweiske** [indieweb/chat.indieweb.org#15]
To support my search engine at indexing, I'd like chat.indieweb.org to support `If-Modified-Since` HTTP request headers, and it should send out Last-Modified HTTP headers for all chat log pages.

**Comment by cweiske** [comment]
Could you do that for day.php and today.php, too?

**Comment by aaronpk** [comment]
`today.php` is always a redirect, do you need a header on that?

`day.php` will be tricky but I can do that. Basically after the day is over it never changes, but for the current day it should never be cached.

**Comment by cweiske** [comment]
Ah, then today.php does not need any change.

day.php - your code description seems sufficient.

**Comment by kevinmarks** [comment]
Last-modified is still useful, especially on the lower traffic channels.
You could set the cache-control policy accordingly, private with a low
max-age for day, public with a very high max-age for archives

On 27 Aug 2016 9:09 am, "Aaron Parecki" <notifications@github.com> wrote:
>
> today.php is always a redirect, do you need a header on that?
>
> day.php will be tricky but I can do that. Basically after the day is over
it never changes, but for the current day it should never be cached.

**Comment by aaronpk** [comment]
@kevinmarks what's the use case for adding cache headers for today's logs?

**Comment by cweiske** [comment]
I also don't see a reason to add cache control headers now. last-modified is enough.
