### ISSUE TITLE
undefined method Config::supported_channels()

### ISSUE THREAD

**Issue by cweiske** [indieweb/chat.indieweb.org#19]
The config template does not contain the `supported_channels` method that is used by `day.php`.

---

Same for

> ( ! ) Fatal error: Call to undefined method Config::logo_for_channel() in /home/cweiske/Dev/tools

and

> Config::related_channels()

**Comment by aaronpk** [comment]
Added in b78f946a04c9f94304ccc73ebf616ec2fdc24782
