### ISSUE TITLE
/* will link to indieweb.org.

### ISSUE THREAD

**Issue by Zegnat** [indieweb/chat.indieweb.org#28]
Not sure if strictly a bug, but I would see it as one. Especially in #dev where wiki updates are shown there are often `/*` strings. WikiMedia surrounds sub-headers in `/*` and `*/` for update messages.

I don’t think it makes sense to autolink these `/*` to `https://indieweb.org/*`.

[Example](https://chat.indieweb.org/dev/2016-09-29/1475173557209000):

> [[[Let's Encrypt](https://indieweb.org/Let's%20Encrypt)]] ! https://indieweb.org/wiki/index.php?diff=31169&oldid=31167&rcid=31113 \* Gregorlove.com \* (+172) [/*](https://indieweb.org/*) IndieWeb Examples */ subheadings, +me

**Comment by aaronpk** [comment]
Fixed in 576fd4b783d3b1937bd1338af4ab61b3b7519e4d
