### ISSUE TITLE
Make #indieweb logs available under /indieweb/

### ISSUE THREAD

**Issue by cweiske** [indieweb/chat.indieweb.org#30]
Because currently it's not possible to search #indieweb logs only by searching for an URL prefix.

**Comment by aaronpk** [comment]
This is a point that we hadn't considered when making the decision to not include `/indieweb` in the URL path for the main channel. It's worth considering, but would be a pretty big change.

**Comment by cweiske** [comment]
The discussion was this: https://indieweb.org/rename_to_IndieWeb#main_channel_at_root_or_not

**Comment by aaronpk** [comment]
Sorta related, I had always imagined being able to search on specific mf2 properties for things like this. That's my plan for my website too. I would search for `micropub channel:indieweb-dev` or if i'm searching my website, `pizza channel:ate`.

**Comment by cweiske** [comment]
phinde currently does not do mf2 parsing apart from using content of `.h-entry` only if it exists. URL filtering is already implemented so it would have been the natural choice:

http://indiechat.search.cweiske.de/?site=chat.indieweb.org/microformats/&q=entry

**Comment by aaronpk** [comment]
This is too big of a change, sorry
