### ISSUE TITLE
Allow WebSub subscriptions

### ISSUE THREAD

**Issue by cweiske** [indieweb/chat.indieweb.org#32]
It would be nice if my search engine https://indiechat.search.cweiske.de/ could subscribe to updates on the main chat pages. This way we could get realtime indexing.

**Comment by aaronpk** [comment]
My plan is to set the hub and topic for the redirect URLs, but not for the URLs that contain day components. e.g. these URLs will all report a rel=self of `https://chat.indieweb.org/dev/`

* `https://chat.indieweb.org/dev`
* `https://chat.indieweb.org/dev/`
* `https://chat.indieweb.org/dev/today`

All three of the above actually end up redirecting to e.g. `https://chat.indieweb.org/dev/2017-11-30`, which will not have WebSub discovery enabled.

When new entries are added to the log, the hub will notify subscribers that the topic `https://chat.indieweb.org/dev/` has changed, the hub will fetch the page and follow the redirect to today's page, then deliver the full page to the subscribers.

Does that match your understanding of how you'd expect this to work?

**Comment by cweiske** [comment]
yes, that should work.
