### ISSUE TITLE
Some permalinks have shifted.

### ISSUE THREAD

**Issue by Zegnat** [indieweb/chat.indieweb.org#38]
[I noticed](https://chat.indieweb.org/meta/2017-12-01/1512117566175800) the permalink I used in #28 no longer works.

|When|Where|
|:------------- |:------------- |
| Previously | `https://chat.indieweb.org/dev/2016-09-29/1475173557209000` |
| Currently | `https://chat.indieweb.org/dev/2016-09-29/1475173557212800` |

It looks like the chat line ID was bumped up by `3800` somewhere during the reworking of the chat log storage.

**Comment by aaronpk** [comment]
From my conversation in IRC:

> ah I know what happened
> those timestamps are microseconds, so divide by 1000000 to get the unix timestamp
> everything after june 11 2016 was logged by both the file logs and the database, so I only imported the DB logs from before that. but that means the timestamps between the two logs differ by a fraction of a second
> so I guess i'll delete all the filesystem logs and re-import from the database :/
