### ISSUE TITLE
Previous/Next buttons missing

### ISSUE THREAD

**Issue by EdwardHinkle** [indieweb/chat.indieweb.org#40]
I go to https://chat.indieweb.org and there are no previous or next buttons. This is the same for every channel.

**Comment by tantek** [comment]
I have seen and heard similar feedback. When in the "wide" layout, the Previous button is in the bottom left column, often scrolled out of view and thus apparently missing.

We should move the Next/Prev buttons at least up to the floating header that has the name of the channel on it. That would also better indicate the context of what you are clicking next/previous for.
