### ISSUE TITLE
Problematic 404 for days-without-chat-messages

### ISSUE THREAD

**Issue by cweiske** [indieweb/chat.indieweb.org#55]
chat.indieweb.org returns a 404 for a date when there are no chat messages at that day, e.g. https://chat.indieweb.org/known/2021-06-14 .

Is there a good reason for this?
My indiechat search indexer gets a 404 and tells me something is wrong every day.

----
There once was #4 which introduced 404s, but I don't think that a 404 should be thrown for an existing channel, even if there are no messages that day.

**Comment by aaronpk** [comment]
Fixed in ca461e3d9c887fcd09cc2d2f42f168fe23f5e08c

Still returns 404 for dates in the future to prevent infinite crawls.
